development:
  secret_key_base: c1e6b8529bfd277b5bd00a3ef5f56526b0b61c0be06232403ebaa54db220d5fc4bca95ca665924e16c5f1535780d64d3705080c5ab7228944564c6299ef581d6
  expier_hour: 300

test:
  secret_key_base: 9b9b4708e9197ab2c699fedbf261a0451bfdb6187bac9b089f463fe7a17d2ad7ffedc77d7da61a6c4bd6c8e9ffa0288f22bdaa6f0e04225fa26fb36a7408cf2c
  expier_hour: 300

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  expier_hour: <%= ENV["EXPIER_HOUR"] %>